### ISSUE TITLE
Let's improve the exercise!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-garcaplay#1]
Really cool job @garcaplay !!!

Here you have some tips to improve the exercise:

- [x] improve the logic to generate and save the random number (remember we gave you a sample code with a function)
- [x] Define the logic to make the counter work. Your solution is creative enough, but we need to solve it the right way.
- [x] Extract the feedback painter to a function

That's it, here you have a Well Done gif!

![Well Done](https://media.giphy.com/media/9g8PH1MbwTy4o/giphy-downsized.gif)

Let me know if you have any doubts ;)

Go for it!!

**Comment by garcaplay** [comment]
Thank you @oneeyedman These improvements have been added to the exercise. Anyway, I am not sure if I have applied correctly the random number logic. 

```
function randomNumber(max){

    return Math.ceil((Math.random()*max)+1);

}
const r = randomNumber(99); 
```

I read on the documentation that math.random could take also 0 as a number, so I think the +1 is necessary (and I cannot set as "max" the 100 because it would transform into a 101).
Nevertheless, you know better how this works, so please let me know if there is a more suitable structure. 

Thank you once again.
Silvia
